allowBuilds:
  esbuild: true
  sharp: true
  tesseract.js: true
onlyBuiltDependencies:
  - esbuild
  - sharp
  - tesseract.js
overrides:
  ip-address: ^10.7.1
  '@esbuild-kit/core-utils>esbuild': ^0.25.12
